### ISSUE TITLE
Update - project_filter Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#14]
## `todo`

- [x] Update project_filter_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #2
   - `@input` :package: [`search_input_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/search-input/search-input.js) from #13 
   - [x] update the project_filter component
   - `@output` :package: [`project_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-filter/project-filter.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/14#issuecomment-1913507130)

---

- [ ] Finalize project_filter_v0.1.?
   - [ ] code project_filter
   - `@output` :package: `project_filter_v0.1.?` from `comment`
   - next #15

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update project_filter_v0.1.0
   - update the project_filter component
   - `@output` :package: [`project_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-filter/project-filter.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
