### ISSUE TITLE
Update - app_projects Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#15]
## `todo`

- [x] Update app_projects_v0.1.0
   - `@input` :package: [`project_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-card/project-card.js) from #6 
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
   - `@input` :package: [`project_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-filter/project-filter.js) from #14 
   - `@input` :package: [`scrollbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/scrollbar/scrollbar.js) from #12 
   - [x] update the app_projects component
   - `@output` :package: [`app_projects_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects/app-projects.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/15#issuecomment-1913509356)

---

- [ ] Finalize app_projects_v0.1.?
   - [ ] code app_projects
   - `@output` :package: `app_projects_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_projects_v0.1.0
   - update the app_projects component
   - `@output` :package: [`app_projects_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects/app-projects.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
