### ISSUE TITLE
Update - projects_page Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#16]
## `todo`

- [x] Update projects_page_v0.1.0
   - `@input` :package: [`app_projects_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects/app-projects.js) from #15 
   - `@input` :package: [`app_footer_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js) from #10 
   - [x] Hide dat visualization component
   - `@output` :package: [`projects_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/f83a934887e0b4225650ca2dd13656a5109f021e#diff-188d8b4676a9d4a719ee299b590ddc588332929d9c3c8cac9622def884bb28e1) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/16#issuecomment-1913511533)

---

- [ ] Finalize projects_page_v0.1.?
   - [ ] code projects_page
   - `@output` :package: `projects_page_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update projects_page_v0.1.0
   - Hide dat visualization component - `2min`
   - Created and logged tasks - `8min`
   - `@output` :package: [`projects_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/f83a934887e0b4225650ca2dd13656a5109f021e#diff-188d8b4676a9d4a719ee299b590ddc588332929d9c3c8cac9622def884bb28e1)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
