### ISSUE TITLE
Update - timeline_filter Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#17]
## `todo`

- [x] Update timeline_filter_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #2
   - `@input` :package: [`search_input_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/search-input/search-input.js) from #13 
   - [x] update the timeline_filter component
   - `@output` :package: [`timeline_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-filter/timeline-filter.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/17#issuecomment-1913513291)

---

- [ ] Finalize timeline_filter_v0.1.?
   - [ ] code timeline_filter
   - `@output` :package: `timeline_filter_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update timeline_filter_v0.1.0
   - update the timeline_filter component
   - `@output` :package: [`timeline_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-filter/timeline-filter.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
