### ISSUE TITLE
Update - year_filter Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#18]
## `todo`

- [x] Update year_filter_v0.1.0
   - [x] update the year_filter component
   - `@output` :package: [`year_filter_v0.1.?`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/year-filter/year-filter.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/18#issuecomment-1913514804)

---

- [ ] Finalize year_filter_v0.1.?
   - [ ] code year_filter
   - `@output` :package: `year_filter_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update year_filter_v0.1.0
   - update the year_filter component
   - `@output` :package: [`year_filter_v0.1.?`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/year-filter/year-filter.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
