### ISSUE TITLE
Update - month_card Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#19]
## `todo`

- [x] Update month_card_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #2
   - [x] update the month_card component
   - `@output` :package: [`month_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-card/month-card.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/19#issuecomment-1913515932)

---

- [ ] Finalize month_card_v0.1.?
   - [ ] code month_card
   - `@output` :package: `month_card_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update month_card_v0.1.0
   - update the month_card component
   - `@output` :package: [`month_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-card/month-card.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
