### ISSUE TITLE
Update - buttons Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#2]
## `todo`

- [x] Update buttons_v0.1.0
   - [x] update icon_button
   - [x] update text_button
   - [x] update logo_button
   - [x] update select_button
   - [x] update sm_icon_button_alt
   - `@output` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/2#issuecomment-1913278380)
---
- [ ] Finalize buttons_v0.1.?
  - [ ] code buttons
  - `@output` :package: `buttons_v0.1.?`

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`

- Update buttons_v0.1.0
   - update icon_button
   - update text_button
   - update logo_button
   - update select_button
   - update sm_icon_button_alt
   - `@output` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons)

---

### worklog

---

### feedback
Initialized the issue

---
### proposals
