### ISSUE TITLE
Update - month_filter Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#20]
## `todo`

- [x] Update month_filter_v0.1.0
   - `@input` :package: [`month_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-card/month-card.js) from #19 
   - `@input` :package: [`scrollbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/scrollbar/scrollbar.js) from #12 
   - [x] update the month_filter component
   - `@output` :package: [`month_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-filter/month-filter.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/20#issuecomment-1913517140)

---

- [ ] Finalize month_filter_v0.1.?
   - [ ] code month_filter
   - `@output` :package: `month_filter_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update month_filter_v0.1.0
   - update the month_filter component
   - `@output` :package: [`month_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-filter/month-filter.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
