### ISSUE TITLE
Update - app_timeline Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#21]
## `todo`

- [x] Update app_timeline_v0.1.0
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3  
   - `@input` :package: [`scrollbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/scrollbar/scrollbar.js) from #12 
   - `@input` :package: [`month_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/month-filter/month-filter.js) from #20 
   - `@input` :package: [`year_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/year-filter/year-filter.js) from #18 
   - `@input` :package: [`timeline_filter_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-filter/timeline-filter.js) from #17 
   - `@input` :package: [`timeline_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-card/timeline-card.js) from #7 
   - [x] fixed timeline / month_filter styling
   - [x] on mobile - fix app_timeline bugs
   - `@output` :package: [`app_timeline_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/462a57f122cb78e6318a80da40af95b4056e0ed9) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/21#issuecomment-1913520469)

---

- [ ] Finalize app_timeline_v0.1.?
   - [ ] code app_timeline
   - `@output` :package: `app_timeline_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_timeline_v0.1.0
   - fixed timeline / month_filter styling - `34min`
   - on mobile - fix app_timeline bugs - `6min`
   - created and logged tasks - `20min`
   - `@output` :package: [`app_timeline_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/462a57f122cb78e6318a80da40af95b4056e0ed9)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
