### ISSUE TITLE
Update - dat_garden Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#24]
## `todo`

- [x] Update dat_garden_v0.1.0
   - `@input` :package: [`comingsoon_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/comingsoon/comingsoon.js) from #23 
   - `@input` :package: [`app_footer_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js) from #10 
   - [x] update the dat_garden component
   - `@output` :package: [`dat_garden_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/dat-garden/dat-garden.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/24#issuecomment-1913551384)

---

- [ ] Finalize dat_garden_v0.1.?
   - [ ] code dat_garden
   - `@output` :package: `dat_garden_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update dat_garden_v0.1.0
   - update the dat_garden component
   - `@output` :package: [`dat_garden_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/dat-garden/dat-garden.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
