### ISSUE TITLE
Update - important_documents Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#26]
## `todo`

- [x] Update important_documents_v0.1.0
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
   - [x] update the important_documents component
   - `@ouptut` :package: [`important_documents_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/important-documents/important-documents.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/26#issuecomment-1913554225)

---

- [ ] Finalize important_documents_v0.1.?
   - [ ] code important_documents
   - `@output` :package: `important_documents_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update important_documents_v0.1.0
   - update the important_documents component
   - `@ouptut` :package: [`important_documents_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/important-documents/important-documents.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
