### ISSUE TITLE
Update - our_members Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#27]
## `todo`

- [x] Update our_members_v0.1.0
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
   - [x] update the our_members component
   - `@ouptut` :package: [`our_members_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-members/our-members.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/27#issuecomment-1913555589)

---

- [ ] Finalize our_members_v0.1.?
   - [ ] code our_members
   - `@output` :package: `our_members_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update our_members_v0.1.0
   - update the our_members component
   - `@ouptut` :package: [`our_members_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-members/our-members.js)

---

### worklog

---

### feedback

Initialized the issue

---

### proposals
