### ISSUE TITLE
Update - our_alumni Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#28]
## `todo`

- [x] Update our_alumni_v0.1.0
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
   - `@input` :package: [`scrollbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/scrollbar/scrollbar.js) from #12 
   - [x] update the our_alumni component
   - `@ouptut` :package: [`our_alumni_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-alumni/our-alumni.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/28#issuecomment-1913556356)

---

- [ ] Finalize our_alumni_v0.1.?
   - [ ] code our_alumni
   - `@output` :package: `our_alumni_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update our_alumni_v0.1.0
   - update the our_alumni component
   - `@ouptut` :package: [`our_alumni_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-alumni/our-alumni.js)

---

### worklog

---

### feedback
Initialize the issue

---

### proposals
