### ISSUE TITLE
Update - info_page Component

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#31]
## `todo`

- [x] Update info_page_v0.1.0 
   - `@input` :package: [`scrollbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/scrollbar/scrollbar.js) from #12 
   - `@input` :package: [`manifesto_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/manifesto/manifesto.js) from #25 
   - `@input` :package: [`important_documents_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/important-documents/important-documents.js) from #26 
   - `@input` :package: [`our_members_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-members/our-members.js) from #27 
   - `@input` :package: [`our_alumni_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/our-alumni/our-alumni.js) from #28 
   - `@input` :package: [`tools_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/tools/tools.js) from #29 
   - `@input` :package: [`app_icon_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-icon/app-icon.js) from #30 
   - [x] on mobile - close all windows by default
   - [x] on mobile - fixed various bugs
   - `@output` :package: [`info_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/675a083637fed5416010607600a969da19d6ffc3) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/31#issuecomment-1913560624)

---

- [ ] Finalize info_page_v0.1.?
   - [ ] code info_page
   - `@output` :package: `info_page_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`
   
- Update info_page_v0.1.0
   - on mobile - close all windows by default - `6min`
   - on mobile - fixed various bugs - `1h34min`
   - created and logged tasks - `14min`
   - `@output` :package: [`info_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/675a083637fed5416010607600a969da19d6ffc3)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
