### ISSUE TITLE
Update - desktop

### ISSUE THREAD

**Issue by alyhxn** [Mehrabbruno/dat-ecosystem#33]
## `todo`

- [x] Update desktop_v0.1.0
   - `@input` :package: [`home_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/home-page/home-page.js) from #11 
   - `@input` :package: [`dat_garden_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/dat-garden/dat-garden.js) from #24 
   - `@input` :package: [`timeline_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-page/timeline-page.js) from #22 
   - `@input` :package: [`projects_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/projects-page/projects-page.js) from #16 
   - `@input` :package: [`info_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/d0e8ce3afb61c645aa527856f9336044209c5890) from #31 
   - `@input` :package: [`navbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/355575f50dc61c43d3f80aa7b839079970acd9ab#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869) from #32 
   - [x] Add scroll_to_top on page switch
   - [x] On mobile - disable pull down refresh
   - [x] Make home as the landing page
   - [x] Go through feedback and provide input (for the whole project)
   - [x] Created all the issues
   - `@output` :package: [`desktop_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/1df116cddd4c55bd42e1abeb3c1c0174f489727d) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/33#issuecomment-1913648224)

---

- [ ] Finalize desktop_v0.1.?
   - [ ] Code desktop
   - `@output` :package: `desktop_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update desktop_v0.1.0
   - Add scroll_to_top on page switch - `7min`
   - On mobile - disable pull down refresh - `5min`
   - Make home as the landing page - `2min`
   - Go through feedback and provide input (for the whole project) - `23min`
   - Created all the issues - `2h30min`
   - Created and logged tasks - `16min`
   - `@output` :package: [`desktop_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/1df116cddd4c55bd42e1abeb3c1c0174f489727d)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
